name: lint
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install uv
      - run: uv pip install --system -r requirements-dev.txt
      - run: ruff check .
      - run: ruff format --check --diff .
