name: test
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install uv
      - run: uv pip install --no-cache --system -r requirements-dev.txt
      # TODO: figure out why `pytest` doesn't discover tests in `faster_whisper_server` directory by itself
      - run: pytest faster_whisper_server/* tests
